apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{.Values.wordpressNamespace}}
  labels:
    name: wordpress
spec:
  type: {{.Values.wordpressServiceType}}
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim3
  namespace: {{.Values.wordpressNamespace}}
  labels:
    app: wordpress
spec:
  storageClassName: {{.Values.storageClassType}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.mysqlStorageSize}}
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  namespace: {{.Values.wordpressNamespace}}
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: {{.Values.registry}}wordpress:{{.Values.wordpressTag}}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim3
      nodeSelector:
        front: "true" # uses this to determine which node to attach to

